### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by Zaturrby** [augmenting-masterpieces/AugmentM#42]
There are a lot of issues with the content! @JBarnbeck 
1. First block has lorem ipsum. I think that's bad, but I might be wrong. 
2. About had some fictional address to the middle of nowhere. People don't have text either
3. To make the video's fullscreen I deleted the under titles, and kind of positioned the text block in that position. Perhaps the video's need a bit of clarification now.
4. I highly doubt the literature is completely accurate, since this is still a copy of a very old list I think.

**Comment by JBarnbeck** [comment]
1. We had agreed not to include the graphics on the second page as it would be too much work to style it. In this styling it's not possible to add it to the site. 
2. In the file with the overall webiste text, are also included the about texts. I'll fix that. 
3. The captions should go back to the videos, also here we had agreed to position them next to the text block with captions underneath. 
4. Also the literature we agreed to leave out as it does not fit with the categories.
