### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by Zaturrby** [augmenting-masterpieces/AugmentM#44]
- Entirely separate page with all the credits and stuffs on it.
- Link in footer

**Comment by Zaturrby** [comment]
@JBarnbeck -> I understand what it's about, but how much and in what shape the content is eludes me. The content, or perhaps a drawing of the page would be nice. (e. g. are we going to show names with pictures? or are we perhaps going to show logos with a list of names underneath? Is all going to be text?) -> I need some idea of where to go with it.  

(Until then I'll provide a blank page under impressum, which is, strangely enough, much harder)

**Comment by Zaturrby** [comment]
Well, lovely nav bug it is. Lovely. Charming, wonderful. It broke the solution of the fluid nav-scroll. I knew it was bad. Now I know why. Complex routing scheme's don't like it. And adding a page made it just complex enough to break down. The links where simple ids, but on the impressum you also need to change state. Yet if I make the links change state, they won't anchorscroll to id's at all. 

So I needed a better solution. ui-sref seemed to provide it. Now the href's are assigned dynamicly. Yet there is still no scroll. So what do you od then, you add another ng-click with a scrolling function to the element. Well lovely. That doens't work either, it fire's before $statechangesucces. But before you know that you have to find out how the viewmodel works, something I have miraculously avoided. It was on the to do list for the masonry. Well, that's easy now. 

Luckily the ui-sref and .state have more to it than that. You can also give parameters. Which you'll be able to call upon and call upon on that lovely $statechangesucces. This way the variables can transfered variables trough the url (which the outside world will love too). So it should work. No syntax errors. All well and good. But noooo. its not working. 

My prediction that providing a empty page is the hardest part proves to be true. What it boils down to: Links don't work on the impressum page.

**Comment by Zaturrby** [comment]
Got it! nav was in the parent state while the $stateParams provides is only set for the child. Information is being transmitted so it's only a small step to excecuting a function with this knowledge.

**Comment by Zaturrby** [comment]
From here on out it'll probably take me an hour or three to final product.

**Comment by Zaturrby** [comment]
Oke, got the data in properly there is now a "scrollTo" attribute on the URL ready to be used when wanted, and not in conflict with the routing scheme. Now there are two steps left to resolve. 

1. On $stateChangeCompleted the navigation controller needs to check for it and scroll to, but only when $stateCurrent is home.subroutes. The $anchorScroll service, or $uiAnchorScroll (something) service, will handle the scrolling, with an Y-offset of 50px, due to the navbar offsetting every ID by that amount.  

2. Step two will be making the $anchorScroll provide a fluid scroll. This'll be the easy part. There is some prefab code for this. Hopefully it used ngAnimate so we lose the jQuery stuff too. Although we have it loaded I don't like it. There is much unnecessary duplication of features in the app. (should be removed from masonry too.)

**Comment by Zaturrby** [comment]
Meh... It'll work.... But it reloads the page even when on the same page. Meaning it won't be a fluid as we had before, unless there is someway to prevent state change. Jumped to quickly once again.

**Comment by Zaturrby** [comment]
Click eater is working. But its too hungry right now. It only needs to eat sref's. It may not eat clicks, because though need to active scrolling code. Somehow the solution feels dirty though. There must be a better way.

**Comment by Zaturrby** [comment]
What I'm trying sounds off, I want to suppress the default behavior of links. A link that doesn't "link", but scrolls. There is some conceptual overlap though. It might not send a proper http request, but it does direct a user to content, which is what links are about. So HTML invented a neat feature for this, let put an # in front of a normal link that suppresses default behavior to make this possible. 

Yet, here comes UI-router, with ui-sref instead of href. A link does not "link" to a proper page/file anymore, but to a state. Now we can avoid the nasty slow buggers called http-requests, and execute much finer control over our applications variables. Yet we loved that hacky hashtag link thing that html provided. And why not? It's good. **And it allows for it.** No problems. Although they didn't add it to the code for their ui-sref, so we can't use that. Although there where some attempts, and they're fine with it, but they haven't got it on the roadmap it seems. (there where some active discussions on the topic, deep in december 2014, a few weeks ago) 

But here's the twist. We're also running Angular-Strap Scrollspy to light up the links. Bootstrap.js but then the angular way. Works like a charm! However.... It gets the information it needs from the href field. You see where this is going? And it like it formatted like href="#someid". While this wasn't a problem when we had a single page, now that we want more the href needs to have a little bit more information. We don't wanna go to "#someid" on the impressum page. We want to go to "#someid" on the homepage. It doesn't like "home#someid", which would be the proper solution, logical, since the it doesn't suppress default behavior, it activates an http-request. A hash is needed at the start. 

But if we use ui-sref they're not there either. Both true and false. It does generate those, apparently, and luckily, after Angular-Strap sets itself up. To Angular-strap they're not there. Angular-Strap then falls back to the "data-target" attribute, possibly to account for the odd situation when it needs to light up something else than a link. A duplication I accidentally left in, that prevented a later problem. But I'm realizing this just now. UI-sref didn't seem to break Angular-strap though. 

However I was dealing with the problem that I coudn't get a hash in the url with it. I ended up creating routes like "home?scrollTo=main" or "home/main". Yet these thing don't have a hash, so they cannot use the default $anchorScroll services. Not that coding one yourself is that hard.. It is messy, wanted to avoid that. And it introduced a new problem. ui-sref default behavior is, as you'd expect to change state on-click. But we don't want that, actually we only want that on the impressum state. It makes scrolling laggy as hell, as the browser get the entire page fed again. So we want to suppress it's default behavior.... Oke, some kid programmed a ui-sref-disable (or eat-click-if) directive, prefect, just what we need. Lets use that to suppress the ui-sref from activation if we're in the same state. Worked like a charm... On the impressum state. 

The click eater is too damned hungry. It eats the click right at the moment it's clicked. On the homestate it actually need to do something too: scroll - and update the url. I need to run a function on click. But when I set it to allow propagation of the event, it activates the ui-sref default state changing behavior. So I need a way to suppress default behavior, while maintaining the possibility of an ng-click directive.

But it's already layer over layer on top of layer. My li's are looking like this:

>   <li bs-scrollspy data-target="#analyse"><a ui-sref="home.subroutes({ scrollTo: 'analyse'})" ng-click="nav.scroller('#analyse')" eat-click-if="nav.stateBoolean">Analyse <span class="hidden-sm hidden-md">and Ideate</span></a></li>

Which is a bit messy.

Conceptually i think its gets down to this: we're using a sub-navigation menu for site wide navigation when we introduce the impressum page. On top of that there is too much shit happening with one variable. Angular-straps scrollspy uses the href attribute, #anchorScroll needs it to go to the proper ids and UI-router is lord and master over the whole thing. Its too much, fix one break the other. I'm going in circles, ending up using technologies way to complicated to solve real simple problems. 

I need to go back the the drawing board with this.

**Comment by Zaturrby** [comment]
Its unsolvable in a simple fashion because its conceptually wrong. Having a subnavigation menu sitewide is weird. It makes sense to simply swap out the partials in this light. That fixes it too.

**Comment by Zaturrby** [comment]
This is going to work. There is just a silly bug left that shouldn't be there.

**Comment by Zaturrby** [comment]
It works! Now it needs it content!

**Comment by JBarnbeck** [comment]
I added a first draft with content. Needs some additions.

Also put the disclaimer text on the site, it is referring to German law however. Still have to figure out the legal situation etc., but for now it should be fine.

**Comment by JBarnbeck** [comment]
...didn't mean to close it.

I added a first draft with content. Needs some additions.

Also put the disclaimer text on the site, it is referring to German law however. Still have to figure out the legal situation etc., but for now it should be fine.

**Comment by Zaturrby** [comment]
I'll update it with some styling too, it's a bit unreadable now.

**Comment by Zaturrby** [comment]
Styling added with cc3abc0
