### ISSUE TITLE
Refactor About to use bootstrap subcolumns

### ISSUE THREAD

**Issue by Zaturrby** [augmenting-masterpieces/AugmentM#65]
About was never tested with actual text in it, which is revealing a little bug right now. Refactoring it to a proper bootstrap grid will fix this.

**Comment by JBarnbeck** [comment]
Yes, we only said at some point, that it should work with 50 words max. each description. So should be ok block-wise.

**Comment by Zaturrby** [comment]
Yeah, it's not hard, and it'll probably fit nicely. We just used a float: left within the column, actually copied from the old site, which didn't cause a problem with only 2 words. But now that it's fifty it needs a bit more explicit guidance.

**Comment by Zaturrby** [comment]
Pretty much finished and deployed already. Might need a minor tweak or two though.

**Comment by Zaturrby** [comment]
Do you like it with or without (header) or (p) name?

**Comment by JBarnbeck** [comment]
I like <p> better. Names <b> in the text. 

Looking at it now.. we didn't include the logo's of the UvA and Rijks yet. Let's fit them where the address is at the moment! Contact only includes of a email adress then.

**Comment by JBarnbeck** [comment]
Let's take out the MediaLab section and Shailoh's picture. The information is outdated, so it doesnt provide useful information for the reader.
Instead we put the logo's of the private contributors on the right side as well. Underneath the Uva/Rijks logo: UncInc, Screenturner and resultat.

**Comment by Zaturrby** [comment]
Alright, sounds (and looks) like it'll be quite different. Something like this?
![img_6503](https://cloud.githubusercontent.com/assets/7668506/5737123/c2eff944-9bdd-11e4-9f7b-b68abd3f36c7.JPG)

**Comment by JBarnbeck** [comment]
No, we can just leave the distribution of the page. Just small logo's on the right hand side, without the texts. 
LEFT:
About (pics & text) 
Augmenting Masterpieces
JB
JHH
PJ
RJK

RIGHT:
logo's Rijks, UvA

Mailing list
form

Private partners (can be next to each other as well)
UncInc
Screenturner
resultat

Mailing list

**Comment by Zaturrby** [comment]
![img_6504](https://cloud.githubusercontent.com/assets/7668506/5738144/4041dcb8-9be9-11e4-8b3d-ca8724f666d8.JPG)

Ongeveer zo? De header lijkt een beetje raar met het logo, dus die heb ik aangepast getekend. Je kan jouw aanpassing life op .eu zien.

**Comment by Zaturrby** [comment]
Heb jij trouwens een logotje van resultat? Ik kan hun website niet vinden.

**Comment by Zaturrby** [comment]
nm. found it.

**Comment by JBarnbeck** [comment]
Looking pretty good! 

Some little tweaks with the styling and the right linkage to resultat and centre for digital humanities. Also "partners" we don't need to say again. 

btw. both Patty and you can of course re-write your own description if you like.

**Comment by Zaturrby** [comment]
This one is getting somewhere. I do still feel that placing the logo as equal to pictures feels off somehow. But it'll do for now. logo's are visible, margins are a little bit more kalibrated (picture line up nicely because they don't have whitespace in themselves anymore. ) etc. Made the Resultat logo black, so its visible now. Closing this for now.
